In [1]:
# Importando as bibliotecas
import requests
import pandas as pd
import warnings
import json

In [3]:
# Consultando todos os campos e dados que retornam de uma consulta na API do TMDB

api_key = "Minha Chave API TMDB"
movie_id = 105
url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}"

response = requests.get(url)
data = response.json()

print(json.dumps(data, indent=4))

{
    "adult": false,
    "backdrop_path": "/5bzPWQ2dFUl2aZKkp7ILJVVkRed.jpg",
    "belongs_to_collection": {
        "id": 264,
        "name": "Back to the Future Collection",
        "poster_path": "/5Xsu2o5IsZRuuxCEVZ9nVve21FP.jpg",
        "backdrop_path": "/AqQotqj7XOI6GjB28nhMMa8YzOT.jpg"
    },
    "budget": 19000000,
    "genres": [
        {
            "id": 12,
            "name": "Adventure"
        },
        {
            "id": 35,
            "name": "Comedy"
        },
        {
            "id": 878,
            "name": "Science Fiction"
        }
    ],
    "homepage": "http://www.backtothefuture.com/movies/backtothefuture1",
    "id": 105,
    "imdb_id": "tt0088763",
    "original_language": "en",
    "original_title": "Back to the Future",
    "overview": "Eighties teenager Marty McFly is accidentally sent back in time to 1955, inadvertently disrupting his parents' first meeting and attracting his mother's romantic interest. Marty must repair the damage to history by rekindling his parents' romance and - with the help of his eccentric inventor friend Doc Brown - return to 1985.",
    "popularity": 68.999,
    "poster_path": "/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg",
    "production_companies": [
        {
            "id": 33,
            "logo_path": "/8lvHyhjr8oUKOOy2dKXoALWKdp0.png",
            "name": "Universal Pictures",
            "origin_country": "US"
        },
        {
            "id": 56,
            "logo_path": "/cEaxANEisCqeEoRvODv2dO1I0iI.png",
            "name": "Amblin Entertainment",
            "origin_country": "US"
        }
    ],
    "production_countries": [
        {
            "iso_3166_1": "US",
            "name": "United States of America"
        }
    ],
    "release_date": "1985-07-03",
    "revenue": 381109762,
    "runtime": 116,
    "spoken_languages": [
        {
            "english_name": "English",
            "iso_639_1": "en",
            "name": "English"
        }
    ],
    "status": "Released",
    "tagline": "He's the only kid ever to get into trouble before he was born.",
    "title": "Back to the Future",
    "video": false,
    "vote_average": 8.312,
    "vote_count": 18076
}

## Franquia Senhor dos Anéis (2001 - 2014)

In [46]:
# Pesquisando por todas as ocorrências de O Senhor dos Anéis

url_search = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=pt-BR&query=O Hobbit%"
response_search = requests.get(url_search)
data_search = response_search.json()

for movie in data_search['results']:
    print(f"ID do filme: {movie['id']}")
    print(f"Título do filme: {movie['title']}")
    print(f"Resumo do filme: {movie['overview']}")
    print("\n")

ID do filme: 49051
Título do filme: O Hobbit: Uma Jornada Inesperada
Resumo do filme: Como a maioria dos hobbits, Bilbo Bolseiro leva uma vida tranquila até o dia em que recebe uma missão do mago Gandalf. Acompanhado por um grupo de anões, ele parte numa jornada até a Montanha Solitária para libertar o Reino de Erebor do dragão Smaug.


ID do filme: 122917
Título do filme: O Hobbit: A Batalha dos Cinco Exércitos
Resumo do filme: O dragão Smaug lança sua fúria ardente contra a Cidade do Lago que fica próxima da montanha de Erebor. Bard consegue derrotá-lo, mas, rapidamente, sem a ameaça do dragão, inicia-se uma batalha pelo controle de Erebor e sua riqueza. Os anões, liderados por Thorin, adentram a montanha e estão dispostos a impedir a entrada de elfos, anões e orcs. Bilbo Bolseiro e Gandalf tentam impedir a guerra.


ID do filme: 57158
Título do filme: O Hobbit: A Desolação de Smaug
Resumo do filme: Ao lado de um grupo de anões e de Gandalf, Bilbo segue em direção à Montanha Solitária, onde deverá ajudar seus companheiros a retomar a Pedra de Arken. O problema é que o artefato está perdido em meio a um tesouro protegido pelo temido dragão Smaug.


ID do filme: 1362
Título do filme: O Hobbit
Resumo do filme: O Hobbit é um 1977 de animação musical especial de televisão criada por Rankin / Bass , um estúdio conhecido por seus especiais de férias, e animado por Topcraft , um precursor do Studio Ghibli , com letras adaptadas do livro. O filme é uma adaptação do 1937 o livro de mesmo nome de JRR Tolkien e foi transmitido pela primeira vez na NBC no Estados Unidos no domingo, 27 de novembro, 1977. O Lugar é a Terra-Média. Bilbo Bolseiro é o herói e um hobbit pacato que sai em uma perigosa aventura. A aventura mais emocionante que nenhum outro hobbit jamais pensou em ir. Nesta adaptação animada do primeiro livro do grande clássico de J.R.R. Tolkien, Bilbo é chamado para ajudar no resgate de um grande tesouro que fora roubado dos anões por Smaug, o dragão. Eles devem mostrar toda sua bravura na Floresta das Trevas, nas Montanhas Sombrias, enfrentando orcs, aranhas gigantes, trolls comedores de hobbits e muito mais.

In [40]:
# Juntando a trilogia Senhor dos Anéis em um dataframe

warnings.simplefilter(action='ignore', category=FutureWarning)

movie_ids = [120, 121, 122, 49051, 57158, 122917, 122917]
tri_aneis = pd.DataFrame()
for movie_id in movie_ids:
    url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
    response_movie = requests.get(url_movie)
    data_movie = response_movie.json()

    movie_info = {'ID do filme': data_movie['id'],
                  'Título': data_movie['title'],
                  'Data de lançamento': data_movie['release_date'],
                  'Gêneros': [genre['name'] for genre in data_movie['genres']],
                  'Votos': data_movie['vote_count'],
                  'Média de votos': data_movie['vote_average'],
                  'Orçamento': data_movie['budget'],
                  'Receita': data_movie['revenue'],
                  'Visão geral': data_movie['overview']}

    tri_aneis = tri_aneis.append(movie_info, ignore_index=True)

tri_aneis.head(6)

,ID do filme,Título,Data de lançamento,Gêneros,Votos,Média de votos,Orçamento,Receita,Visão geral
0,120,O Senhor dos Anéis: A Sociedade do Anel,2001-12-18,"[Aventura, Fantasia, Ação]",22864,8.399,93000000,871368364,"Em uma terra fantástica e única, um hobbit rec..."
1,121,O Senhor dos Anéis: As Duas Torres,2002-12-18,"[Aventura, Fantasia, Ação]",19875,8.380,79000000,926287400,"Após a captura de Merry e Pippy pelos orcs, a ..."
2,122,O Senhor dos Anéis: O Retorno do Rei,2003-12-01,"[Aventura, Fantasia, Ação]",21756,8.477,94000000,1118888979,O confronto final entre as forças do bem e do ...
3,49051,O Hobbit: Uma Jornada Inesperada,2012-11-26,"[Aventura, Fantasia, Ação]",17114,7.335,250000000,1021103568,"Como a maioria dos hobbits, Bilbo Bolseiro lev..."
4,57158,O Hobbit: A Desolação de Smaug,2013-12-11,"[Fantasia, Aventura, Ação]",12046,7.571,250000000,958400000,"Ao lado de um grupo de anões e de Gandalf, Bil..."
5,122917,O Hobbit: A Batalha dos Cinco Exércitos,2014-12-10,"[Ação, Aventura, Fantasia]",13062,7.311,250000000,956019788,O dragão Smaug lança sua fúria ardente contra ...

## Franquia Matrix (1999 - 2021)

In [27]:
# Pesquisando por todas as ocorrências de Matrix

url_search = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=pt-BR&query=Matrix%"
response_search = requests.get(url_search)
data_search = response_search.json()

for movie in data_search['results']:
    print(f"ID do filme: {movie['id']}")
    print(f"Título do filme: {movie['title']}")
    print(f"Resumo do filme: {movie['overview']}")
    print("\n")

ID do filme: 603
Título do filme: Matrix
Resumo do filme: Em um futuro próximo, Thomas Anderson (Keanu Reeves), um jovem programador de computador que mora em um cubículo escuro, é atormentado por estranhos pesadelos nos quais encontra-se conectado por cabos e contra sua vontade, em um imenso sistema de computadores do futuro. Em todas essas ocasiões, acorda gritando no exato momento em que os eletrodos estão para penetrar em seu cérebro. À medida que o sonho se repete, Anderson começa a ter dúvidas sobre a realidade. Por meio do encontro com os misteriosos Morpheus (Laurence Fishburne) e Trinity (Carrie-Anne Moss), Thomas descobre que é, assim como outras pessoas, vítima do Matrix, um sistema inteligente e artificial que manipula a mente das pessoas, criando a ilusão de um mundo real enquanto usa os cérebros e corpos dos indivíduos para produzir energia. Morpheus, entretanto, está convencido de que Thomas é Neo, o aguardado messias capaz de enfrentar o Matrix e conduzir as pessoas de volta à realidade e à liberdade.


ID do filme: 624860
Título do filme: Matrix Resurrections
Resumo do filme: Em um mundo de duas realidades — a vida cotidiana e o que está por trás dela —, Thomas Anderson terá que escolher seguir o coelho branco mais uma vez. A escolha, embora seja uma ilusão, ainda é a única maneira de entrar ou sair da Matrix, que é mais forte, mais segura e mais perigosa do que nunca.


ID do filme: 604
Título do filme: Matrix Reloaded
Resumo do filme: Após derrotar as máquinas em seu combate inicial, Neo ainda vive na Nabucodonosor ao lado de Morpheus, Trinity e Link, o novo tripulante da nave. As máquinas estão realizando uma grande ofensiva contra Zion, onde 250 mil delas escavam rumo à cidade e podem alcançá-la em poucos dias. A Nabucodonosor é convocada para retornar a Zion e participar da reunião que definirá o contra-ataque para salvar a humanidade da extinção. Entretanto, um recado enviado pelo Oráculo faz com que Neo retorne à Matrix.


ID do filme: 605
Título do filme: Matrix Revolutions
Resumo do filme: Após enfrentar os sentinelas no mundo real, Neo (Keanu Reeves) tem sua mente presa em um local que fica entre a Matrix e a realidade, do qual apenas poderá sair com a ajuda de Trainman (Bruce Spence). Após perceberem que as ondas cerebrais de Neo são idênticas as de uma pessoa conectada à Matrix, Trinity (Carrie-Anne Moss) e Morpheus (Laurence Fishburne) buscam a ajuda da Oráculo (Mary Alice) e Seraph (Sing Ngai). Trinity, Morpheus e Seraph vão em busca de Merovingian (Lambert Wilson), que possui controle sobre Trainman e pode libertar Neo. Após obterem sucesso no resgate, o trio se divide em duas missões: Enquanto Morpheus e a tripulação de duas naves parte rumo a Zion, na tentativa de ajudar no combate contra as máquinas, Neo e Trinity se dirigem à Cidadela das Máquinas.


ID do filme: 14543
Título do filme: Matrix – Os Segredos de Produção
Resumo do filme: O documentário apresenta detalhes e curiosidades sobre a produção original e toda a trajetória de preparação para as filmagens. É mostrada a coleta de informações pelos diretores Larry e Andrew Wachowski sobre filosofia oriental e a natureza da realidade. Curiosidades como os diversos livros que Keanu Reeves teve de ler antes de conhecer o roteiro, além da influência de Hong Konge das lutas de kung-Fu sobre o filme são explicadas por meio de comentários da equipe e do elenco. Todos os mecanismos e táticas para a realização do filme são revelados no documentário. Vale dizer que a obra está dividida em tópicos para que os mistérios sejam esclarecidos: as locações dos sets na Austrália; o estilo visual; os figurinos; a criação dos efeitos especiais; o treinamento dos atores.


ID do filme: 33322
Título do filme: Armitage III: Poly-Matrix
Resumo do filme: No ano 2046 os seres humanos estão se afastando de usar robôs e começam a confiar cada vez menos neles. Neste tempo, a vida se torna muito perigosa para os seres conhecidos como segundos. Os segundos são a linha mais recente de robôs, até onde o público sabe. Esse é o mundo em que o detetive Ross Sylibus vive. O detetive Sylibus é transferido para Marte por seu pedido depois que seu parceiro foi morto por um robô. À medida que ele chega, ele cai de cabeça num assassinato onde um cantor de país em seu vôo foi assassinado. Ele sai do avião e observa enquanto uma cena se desenrola e ele encontra seu parceiro, Armitage, uma policial com uma atitude importante. Uma série de assassinatos começa quando ainda mais mulheres são mortas. Como a investigação é continuada um segredo é descoberto. Existe outra linha de robôs conhecida como Terços. Mais e mais Terceiros aparecem desaparecidos, como um assassino em série que tem a intenção de aniquilar todos os Terços corre desenfreado.


ID do filme: 21769
Título do filme: Armitage III: Dual-Matrix
Resumo do filme: Alguns anos depois de se conhecerem, Naomi Armitage e Ross Syllabus começaram uma família. Apesar de suas vidas normais, eles devem manter suas identidades em segredo porque muitas pessoas acreditam que os robôs não merecem status igual com os seres humanos. Ross tem uma oportunidade para abolir essas idéias na Terra através de uma votação, mas as organizações nas sombras estão trabalhando para que isso não aconteça.


ID do filme: 221495
Título do filme: The Matrix Recalibrated
Resumo do filme: The making of Matrix Revolutions, The (2003) is briefly touched on here in this documentary. Interviews with various cast and crew members inform us how they were affected by the deaths of Gloria Foster and Aaliyah, and also delve into the making of the visual effects that takes up a lot of screen time. Written by Rhyl Donnelly


ID do filme: 51767
Título do filme: Sexual Matrix
Resumo do filme: A professor designing a machine designed to meet the naughtiest fantasies. In order to perfect the discovery, he performed tests on various subjects, aided by his very appealing assistant.


ID do filme: 591955
Título do filme: The Matrix Reloaded Revisited
Resumo do filme: The making of The Matrix Reloaded:  Go to the middle movie's furthest reaches via five documentary paths revealing 21 featurettes.


ID do filme: 1142175
Título do filme: Matrix Dream Maze
Resumo do filme: Legend has it that people who meet the dream demon are trapped there forever.


ID do filme: 684731
Título do filme: The Matrix Reloaded: Pre-Load
Resumo do filme: This making-of piece offers the standard mix of movie snippets, behind the scenes materials, and interviews from cast and crew on the making of the film.


ID do filme: 684428
Título do filme: The Matrix: What Is Bullet-Time?
Resumo do filme: Special Effects wizard John Gaeta demonstrates how the "Bullet-Time" effects were created for the film Matrix, The (1999).


ID do filme: 696109
Título do filme: A Glitch in the Matrix
Resumo do filme: Are we in fact living in a simulation? This is the question postulated, wrestled with, and ultimately argued for through archival footage, compelling interviews with real people shrouded in digital avatars, and a collection of cases from some of our most iconoclastic figures in contemporary culture.


ID do filme: 555879
Título do filme: Matrix
Resumo do filme: The film is composed of receding planes in a landscape: a back garden and the houses beyond. The wooden lattice fence, visible in the image, marks the border between enclosed and open, private and public space, and forms both a fulcrum for the work and a formal grid by which the shots are framed and organised.


ID do filme: 411948
Título do filme: Matrix I
Resumo do filme: A piece of abstract cinema by John Whitney. A series squares follow a 3-dimensional track, each one with a slight delay after the other.


ID do filme: 503880
Título do filme: The Matrix Revolutions Revisited
Resumo do filme: The making of The Matrix Revolutions:  The cataclysmic final confrontation chronicled through six documentary pods revealing 28 featurettes


ID do filme: 373223
Título do filme: Matrix
Resumo do filme: Abstract art film made for gallery exhibition.


ID do filme: 684431
Título do filme: Making 'The Matrix'
Resumo do filme: A promotional making-of documentary for the film Matrix, The (1999) that devotes its time to explaining the digital and practical effects contained in the film. This is very interesting, seeing as how they're giving away the cinematic secrets that they created solely for the this movie, that have now been spoofed and referenced in countless other films.


ID do filme: 259464
Título do filme: V-World Matrix
Resumo do filme: Two friends take a cyber vacation to experience a world where they can act out their virtual fantasies! They soon realize they've entered a virtual free-for-all. Forbidden fantasies and desires suddenly appear in the form of the even deadlier "dark woman". All the players now end up in a cyber battle for their lives, and sanity, against a beautiful virtual hunter who has one killer fixation - winning the deadly game they started!

In [28]:
# Juntando a trilogia Matrix em um dataframe

warnings.simplefilter(action='ignore', category=FutureWarning)

movie_ids = [603, 604, 605, 624860]
tri_matrix = pd.DataFrame()
for movie_id in movie_ids:
    url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
    response_movie = requests.get(url_movie)
    data_movie = response_movie.json()

    movie_info = {'ID do filme': data_movie['id'],
                  'Título': data_movie['title'],
                  'Data de lançamento': data_movie['release_date'],
                  'Gêneros': [genre['name'] for genre in data_movie['genres']],
                  'Votos': data_movie['vote_count'],
                  'Média de votos': data_movie['vote_average'],
                  'Orçamento': data_movie['budget'],
                  'Receita': data_movie['revenue'],
                  'Visão geral': data_movie['overview']}

    tri_matrix = tri_matrix.append(movie_info, ignore_index=True)

tri_matrix.head()

,ID do filme,Título,Data de lançamento,Gêneros,Votos,Média de votos,Orçamento,Receita,Visão geral
0,603,Matrix,1999-03-30,"[Ação, Ficção científica]",23361,8.204,63000000,463517383,"Em um futuro próximo, Thomas Anderson (Keanu R..."
1,604,Matrix Reloaded,2003-05-15,"[Aventura, Ação, Thriller, Ficção científica]",9925,7.039,150000000,738599701,Após derrotar as máquinas em seu combate inici...
2,605,Matrix Revolutions,2003-11-05,"[Aventura, Ação, Thriller, Ficção científica]",8921,6.707,150000000,424988211,"Após enfrentar os sentinelas no mundo real, Ne..."
3,624860,Matrix Resurrections,2021-12-16,"[Ficção científica, Ação, Aventura]",4818,6.518,190000000,156497322,Em um mundo de duas realidades — a vida cotidi...

## Franquia O Exterminador do Futuro (1984 - 2003)

In [29]:
# Pesquisando por todas as ocorrências de O Exterminador do Futuro

url_search = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=pt-BR&query=O Exterminador do Futuro%"
response_search = requests.get(url_search)
data_search = response_search.json()

for movie in data_search['results']:
    print(f"ID do filme: {movie['id']}")
    print(f"Título do filme: {movie['title']}")
    print(f"Resumo do filme: {movie['overview']}")
    print("\n")

ID do filme: 87101
Título do filme: O Exterminador do Futuro: Gênesis
Resumo do filme: John Connor, líder da resistência humana contra Skynet, envia Kyle Reese de volta a 1984 para proteger sua mãe, Sarah. Porém, Reese se surpreende ao encontrá-la com um exterminador que age como seu protetor, e descobre que o passado foi alterado.


ID do filme: 218
Título do filme: O Exterminador do Futuro
Resumo do filme: Em um futuro próximo, a guerra entre humanos e máquinas foi iniciada. Com a tecnologia a seu dispor, um plano inusitado é arquitetado pelas máquinas ao enviar para o passado um andróide com a missão de matar a mãe daquele que viria a se transformar num líder e seu pior inimigo. Contudo, os humanos também conseguem enviar seu representante para proteger a mulher e tentar garantir o futuro da humanidade.


ID do filme: 280
Título do filme: O Exterminador do Futuro 2: O Julgamento Final
Resumo do filme: O jovem John Connor é a chave para a vitória da civilização sobre uma rebelião de robôs do futuro. No entanto, ele torna-se alvo de T-1000, um exterminador que pode assumir a forma que desejar e que foi enviado do futuro para matá-lo. Outro exterminador, o renovado T-800, também é enviado de volta ao passado para proteger o garoto. Quando John e sua mãe embarcam na fuga com T-800, o menino cria um vínculo forte e inesperado com o robô.


ID do filme: 534
Título do filme: O Exterminador do Futuro 4: A Salvação
Resumo do filme: John Connor é designado para liderar a resistência humana ao domínio das máquinas, coordenadas pela Skynet e seu exército de exterminadores. Quando surge um estranho homem chamado Marcus Wright, cuja última memória que possui é de estar no corredor da morte. John Connor precisa descobrir se ele foi enviado do futuro ou resgatado do passado, ao mesmo tempo em que a Skynet prepara seu ataque definitivo, que pode aniquilar a humanidade.


ID do filme: 290859
Título do filme: O Exterminador do Futuro: Destino Sombrio
Resumo do filme: Décadas após Sarah Connor impedir o Dia do Julgamento, um novo Exterminador letal é enviado para eliminar o futuro líder da resistência. Em uma luta para salvar a humanidade, Sarah Connor, endurecida pela batalha, se une a um aliado inesperado e a um super soldado aprimorado com a missão de parar o Exterminador mais mortal até agora.


ID do filme: 296
Título do filme: O Exterminador do Futuro 3: A Rebelião das Máquinas
Resumo do filme: Na intenção de concluir a missão ainda inacabada, a bela e perigosa máquina mortífera T-X é enviada para matar John Connor, líder da resistência humana contra as máquinas da Skynet. Para protegê-lo mais uma vez o ciborgue T-800 volta à cena.

In [41]:
# Juntando a trilogia clássica de O Exterminador do Futuro em um dataframe

warnings.simplefilter(action='ignore', category=FutureWarning)

movie_ids = [218, 280, 296, 534, 87101, 290859]
tri_ext = pd.DataFrame()
for movie_id in movie_ids:
    url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
    response_movie = requests.get(url_movie)
    data_movie = response_movie.json()

    movie_info = {'ID do filme': data_movie['id'],
                  'Título': data_movie['title'],
                  'Data de lançamento': data_movie['release_date'],
                  'Gêneros': [genre['name'] for genre in data_movie['genres']],
                  'Votos': data_movie['vote_count'],
                  'Média de votos': data_movie['vote_average'],
                  'Orçamento': data_movie['budget'],
                  'Receita': data_movie['revenue'],
                  'Visão geral': data_movie['overview']}

    tri_ext = tri_ext.append(movie_info, ignore_index=True)

tri_ext.head(6)

,ID do filme,Título,Data de lançamento,Gêneros,Votos,Média de votos,Orçamento,Receita,Visão geral
0,218,O Exterminador do Futuro,1984-10-26,"[Ação, Thriller, Ficção científica]",11581,7.600,6400000,78371200,"Em um futuro próximo, a guerra entre humanos e..."
1,280,O Exterminador do Futuro 2: O Julgamento Final,1991-07-03,"[Ação, Thriller, Ficção científica]",11443,8.100,102000000,520000000,O jovem John Connor é a chave para a vitória d...
2,296,O Exterminador do Futuro 3: A Rebelião das Máq...,2003-07-02,"[Ação, Thriller, Ficção científica]",5941,6.144,200000000,435000000,Na intenção de concluir a missão ainda inacaba...
3,534,O Exterminador do Futuro 4: A Salvação,2009-05-20,"[Ação, Ficção científica, Thriller]",5889,6.039,200000000,371353001,John Connor é designado para liderar a resistê...
4,87101,O Exterminador do Futuro: Gênesis,2015-06-23,"[Ficção científica, Ação, Thriller, Aventura]",7731,5.920,155000000,440603537,"John Connor, líder da resistência humana contr..."
5,290859,O Exterminador do Futuro: Destino Sombrio,2019-10-23,"[Ficção científica, Ação]",4532,6.459,185000000,261119292,Décadas após Sarah Connor impedir o Dia do Jul...

## Trilogia De Volta para o Futuro (1985 - 1990)

In [31]:
# Pesquisando por todas as ocorrências de De Volta para o Futuro

url_search = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=pt-BR&query=De Volta para o Futuro%"
response_search = requests.get(url_search)
data_search = response_search.json()

for movie in data_search['results']:
    print(f"ID do filme: {movie['id']}")
    print(f"Título do filme: {movie['title']}")
    print(f"Resumo do filme: {movie['overview']}")
    print("\n")

ID do filme: 105
Título do filme: De Volta para o Futuro
Resumo do filme: Marty McFly, um típico adolescente americano dos anos 80, acidentalmente é enviado de volta ao ano de 1955 em um carro modificado para ser uma máquino do tempo, inventada por um cientista louco. Durante sua fantástica e maluca viagem no tempo, McFly tem que fazer com que seus futuros pais se encontrem e se apaixonem, para que assim ele possa ir de volta para o futuro.


ID do filme: 165
Título do filme: De Volta para o Futuro II
Resumo do filme: Uma despretensiosa visita de McFly e Doc ao ano de 2015 revela alguns problemas com a futura família de McFly. Mas quando os dois voltam para casa, logo descobrem que alguém alterou a linha temporal e criou uma terrível Hill Valley em 1985. A única esperança é poder voltar de novo para o ano de 1995 e salvar o futuro.


ID do filme: 196
Título do filme: De Volta para o Futuro III
Resumo do filme: Presos em 1955 depois de um estranho estouro de luz, McFly tem que viajar para o ano de 1885 para resgatar Doc Brown de uma morte prematura. Depois de sobreviver a um ataque de índios hostis e de moradores da cidade nada amigáveis, McFly encontra Doc Brown. Mas com Doc apaixonado pela charmosa Clara Clayton, está nas mãos de McFly conseguir tirá-los do velho oeste e voltar para o futuro.


ID do filme: 373801
Título do filme: De Volta Para O Presente
Resumo do filme: De Volta para o Futuro, de Steven Spielberg, foi um grande sucesso de bilheteria em 1985, que acabou levando a duas sequências.  Em 1989, em De Volta para o Futuro Parte II, Michael J. Fox, também conhecido como Marty McFly e Christopher Lloyd, também conhecido como Doc Brown, viajam para o futuro até 21 de outubro de 2015.  Na época, as invenções malucas do filme pareciam longe de ser alcançáveis, mas mal sabíamos que estariam tão perto da realidade.  O elenco e os cineastas analisam a franquia cult e discutem carros autônomos, pranchas flutuantes, TVs de tela plana, imagens projetadas e realidade virtual.  Na encruzilhada do entretenimento, cultura pop e ciência, Back to the Future ainda ressoa com as gerações que cresceram assistindo a esses filmes cult.

In [32]:
# Juntando a trilogia De Volta para o Futuro em um dataframe

warnings.simplefilter(action='ignore', category=FutureWarning)

movie_ids = [105, 165, 196]
tri_futuro = pd.DataFrame()
for movie_id in movie_ids:
    url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
    response_movie = requests.get(url_movie)
    data_movie = response_movie.json()

    movie_info = {'ID do filme': data_movie['id'],
                  'Título': data_movie['title'],
                  'Data de lançamento': data_movie['release_date'],
                  'Gêneros': [genre['name'] for genre in data_movie['genres']],
                  'Votos': data_movie['vote_count'],
                  'Média de votos': data_movie['vote_average'],
                  'Orçamento': data_movie['budget'],
                  'Receita': data_movie['revenue'],
                  'Visão geral': data_movie['overview']}

    tri_futuro = tri_futuro.append(movie_info, ignore_index=True)

tri_futuro.head()

,ID do filme,Título,Data de lançamento,Gêneros,Votos,Média de votos,Orçamento,Receita,Visão geral
0,105,De Volta para o Futuro,1985-07-03,"[Aventura, Comédia, Ficção científica]",18072,8.313,19000000,381109762,"Marty McFly, um típico adolescente americano d..."
1,165,De Volta para o Futuro II,1989-11-22,"[Aventura, Comédia, Ficção científica]",11582,7.752,40000000,332000000,Uma despretensiosa visita de McFly e Doc ao an...
2,196,De Volta para o Futuro III,1990-05-25,"[Aventura, Comédia, Ficção científica]",9481,7.466,40000000,244527583,Presos em 1955 depois de um estranho estouro d...

## Franquia de Star Wars (Episódios I a IX, 1977 - 2019)

In [33]:
# Pesquisando por todas as ocorrências de Guerra nas Estrelas

url_search = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=pt-BR&query=Guerra nas Estrelas%"
response_search = requests.get(url_search)
data_search = response_search.json()

for movie in data_search['results']:
    print(f"ID do filme: {movie['id']}")
    print(f"Título do filme: {movie['title']}")
    print(f"Resumo do filme: {movie['overview']}")
    print("\n")

ID do filme: 11
Título do filme: Guerra nas Estrelas
Resumo do filme: A princesa Leia é mantida refém pelas forças imperiais comandadas por Darth Vader. Luke Skywalker e Han Solo precisam libertá-la e restaurar a liberdade e a justiça na galáxia.


ID do filme: 1891
Título do filme: Guerra nas Estrelas: O Império Contra-Ataca
Resumo do filme: As forças imperais comandadas por Darth Vader lançam um ataque contra os membros da resistência, que são obrigados a fugir. Enquanto isso Luke Skywalker tenta encontrar o Mestre Yoda, que poderá ensiná-lo a dominar a "Força" e torná-lo um cavaleiro jedi. No entanto, Darth Vader planeja levá-lo para o lado negro da "Força".


ID do filme: 1892
Título do filme: Guerra nas Estrelas: O Retorno de Jedi
Resumo do filme: O imperador está supervisionando a construção de uma nova Estrela da Morte. Enquanto isso Luke Skywalker liberta Han Solo e a Princesa Leia das mãos de Jaba. Luke só se tornará um cavaleiro jedi quando destruir Darth Vader, que ainda pretende atraí-lo para o lado sombrio da Força.


ID do filme: 74849
Título do filme: Guerra nas Estrelas - Especial de Natal
Resumo do filme: Luke Skywalker e Han Solo lutam contra as forças imperiais do mal para ajudar Chewbacca a alcançar sua família em perigo no planeta Wookiee - a tempo para o Dia da Vida, o dia mais importante do ano!


ID do filme: 330459
Título do filme: Rogue One: Uma História Star Wars
Resumo do filme: Em busca de uma nova esperança para a galáxia, a Aliança Rebelde enfrenta uma arriscada missão: roubar os planos que revelam uma falha na construção da Estrela da Morte. Para isso, eles contam com a ajuda de Jyn Erso, filha do criador da arma mais poderosa do império.


ID do filme: 1894
Título do filme: Star Wars: Episódio II - Ataque dos Clones
Resumo do filme: Com a missão de proteger a Senadora Amidala, Anakin Skywalker descobre o seu amor por ela, do mesmo modo que vai conhecendo seu lado sombrio. Obi-Wan Kenobi descobre um exército de clones à medida que a Galáxia caminha para uma grande guerra.


ID do filme: 1893
Título do filme: Star Wars: Episódio I - A Ameaça Fantasma
Resumo do filme: Enquanto resgatam a Rainha Amidala, governante de um planeta pacífico invadido por forças ameaçadoras, os Cavaleiros Jedi Obi-Wan Kenobi e Qui-Gon Jinn descobrem Anakin Skywalker, uma criança prodígio de 9 anos excepcionalmente poderosa na Força.


ID do filme: 1895
Título do filme: Star Wars: Episódio III - A Vingança dos Sith
Resumo do filme: As Guerras Clônicas estão em pleno andamento e Anakin Skywalker mantém um elo de lealdade com Palpatine, ao mesmo tempo em que luta para que seu casamento com Padmé Amidala não seja afetado por esta situação. Seduzido por promessas de poder, Anakin se aproxima cada vez mais de Darth Sidious até se tornar o temível Darth Vader. Juntos eles tramam um plano para aniquilar de uma vez por todas com os cavaleiros jedi.

In [42]:
# Juntando a trilogia Clássica de Star Wars em um dataframe

warnings.simplefilter(action='ignore', category=FutureWarning)

movie_ids = [11, 1891, 1892, 1893, 1894, 1895, 140607, 181808, 181812]
tri_sw_cla = pd.DataFrame()
for movie_id in movie_ids:
    url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
    response_movie = requests.get(url_movie)
    data_movie = response_movie.json()

    movie_info = {'ID do filme': data_movie['id'],
                  'Título': data_movie['title'],
                  'Data de lançamento': data_movie['release_date'],
                  'Gêneros': [genre['name'] for genre in data_movie['genres']],
                  'Votos': data_movie['vote_count'],
                  'Média de votos': data_movie['vote_average'],
                  'Orçamento': data_movie['budget'],
                  'Receita': data_movie['revenue'],
                  'Visão geral': data_movie['overview']}

    tri_sw_cla = tri_sw_cla.append(movie_info, ignore_index=True)

tri_sw_cla.head(10)

,ID do filme,Título,Data de lançamento,Gêneros,Votos,Média de votos,Orçamento,Receita,Visão geral
0,11,Guerra nas Estrelas,1977-05-25,"[Aventura, Ação, Ficção científica]",18786,8.203,11000000,775398007,A princesa Leia é mantida refém pelas forças i...
1,1891,Guerra nas Estrelas: O Império Contra-Ataca,1980-05-20,"[Aventura, Ação, Ficção científica]",15455,8.392,18000000,538400000,As forças imperais comandadas por Darth Vader ...
2,1892,Guerra nas Estrelas: O Retorno de Jedi,1983-05-25,"[Aventura, Ação, Ficção científica]",14305,7.889,32350000,572700000,O imperador está supervisionando a construção ...
3,1893,Star Wars: Episódio I - A Ameaça Fantasma,1999-05-19,"[Aventura, Ação, Ficção científica]",13297,6.531,115000000,924317558,"Enquanto resgatam a Rainha Amidala, governante..."
4,1894,Star Wars: Episódio II - Ataque dos Clones,2002-05-15,"[Aventura, Ação, Ficção científica]",12056,6.553,120000000,649398328,"Com a missão de proteger a Senadora Amidala, A..."
5,1895,Star Wars: Episódio III - A Vingança dos Sith,2005-05-17,"[Aventura, Ação, Ficção científica]",12507,7.407,113000000,850000000,As Guerras Clônicas estão em pleno andamento e...
6,140607,Star Wars: O Despertar da Força,2015-12-15,"[Aventura, Ação, Ficção científica]",18113,7.296,245000000,2068223624,A queda de Darth Vader e do Império levou ao s...
7,181808,Star Wars: Episódio VIII - Os Últimos Jedi,2017-12-13,"[Aventura, Ação, Ficção científica]",14077,6.833,200000000,1332698830,A tranquila e solitária vida de Luke Skywalker...
8,181812,Star Wars: Episódio IX - A Ascensão Skywalker,2019-12-18,"[Aventura, Ação, Ficção científica]",8828,6.381,250000000,1074144248,"Com o retorno do Imperador Palpatine, todos vo..."

## Franquia Mad Max (1979 - 2015)

In [35]:
# Pesquisando por todas as ocorrências de Mad Max

url_search = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=pt-BR&query=Mad Max%"
response_search = requests.get(url_search)
data_search = response_search.json()

for movie in data_search['results']:
    print(f"ID do filme: {movie['id']}")
    print(f"Título do filme: {movie['title']}")
    print(f"Resumo do filme: {movie['overview']}")
    print("\n")

ID do filme: 76341
Título do filme: Mad Max: Estrada da Fúria
Resumo do filme: Em um mundo apocalíptico, Max Rockatansky acredita que a melhor forma de sobreviver é não depender de ninguém. Porém, após ser capturado pelo tirano Immortan Joe e seus rebeldes, Max se vê no meio de uma guerra mortal, iniciada pela imperatriz Furiosa que tenta salvar um grupo de garotas. Também tentando fugir, Max aceita ajudar Furiosa. Dessa vez, o tirano Joe está ainda mais implacável pois teve algo insubstituível roubado.


ID do filme: 8810
Título do filme: Mad Max 2: A Caçada Continua
Resumo do filme: No futuro o bem mais precioso é a gasolina, em virtude de uma guerra que acabou com os campos petrolíferos do Oriente Médio. Tendo combustível pode-se fugir da morte ou se dirigir a algum lugar para matar alguém. Neste contexto, Max resolve ajudar uma comunidade a defender sua refinaria contra uma gangue de motoqueiros.


ID do filme: 9355
Título do filme: Mad Max: Além da Cúpula do Trovão
Resumo do filme: Em uma era pós-apocalíptica, Mad Max chega a uma cidade cheia de desordeiros e governada por Turner. Lá, ele se torna um gladiador e é abandonado no deserto. Um bando de órfãos selvagens, os quais procuram por ajuda há muitos anos, acaba resgatando Mad Max. Quando vários dos órfãos acreditam que a chegada de Max é um sinal, ele decide retornar para a cidade.


ID do filme: 9659
Título do filme: Mad Max
Resumo do filme: Em um futuro distópico não muito distante, os recursos de óleo foram esgotados e o mundo está mergulhado em guerra, fome e caos financeiro. É quando o policial Mad Max, que não tem mais nada além de seus instintos de sobrevivência e retaliação, começa uma vingança contra a gangue que perseguiu e assassinou sua esposa e filhos.


ID do filme: 340023
Título do filme: Mad Max: The Wasteland
Resumo do filme:


ID do filme: 307732
Título do filme: Mad Max Renegade
Resumo do filme: Mad Max Renegade follows the further adventures of Max Rockatansky after his desertion from Main Force Patrol in his famed Pursuit Special, more commonly known as the Interceptor.


ID do filme: 692281
Título do filme: Mad.Max
Resumo do filme:


ID do filme: 340266
Título do filme: Mad Max a Wasteland Story
Resumo do filme:


ID do filme: 650738
Título do filme: Mad to The Max: Hoon Nation
Resumo do filme: A look at Aussies Hoodlum culture.


ID do filme: 786892
Título do filme: Furiosa
Resumo do filme: As the world falls, young Furiosa is snatched from the Green Place of Many Mothers into the hands of a great biker horde led by the warlord Dementus. Sweeping through the wasteland, they encounter the citadel presided over by Immortan Joe. The two tyrants wage war for dominance, and Furiosa must survive many trials as she puts together the means to find her way home.


ID do filme: 95414
Título do filme: The Mad Scientist
 Os primeiros nove curtas-metragens foram produzidos pela Fleischer Studios de 1941 a 1942, enquanto os oito restantes foram produzidos pela Famous Studios, a empresa que sucedeu Fleischer Studios, entre 1942 e 1943.


ID do filme: 30927
Título do filme: O Sobrevivente
Resumo do filme: The world's water supply has dried up due to some sort of apocalypse. A beautiful woman holds the secret to where one of the last springs being guarded by a group of Amazons. A "Road Warrior" like crew captures her and tries to make her talk through brutal torture. The hero (Stryker) unites with some of the remaining "good guys" and the Amazons and frees the woman. They go on to a "Road Warrior" type of concluding battle with the bad guys.


ID do filme: 257723
Título do filme: Last Step to Death
Resumo do filme: Ultra hardcore mercenary Kaan, the kind of guy who carries an astonishing amount of large knives on his body at all times, is hired by some guy in a suit with a nervous tic (Patron) to rescue a Professor who has found the cure for leukaemia from some unnamed and unexplained heavily armed evildoers holding him somewhere out in the country. Tic guy is willing to pay Kaan 100 million TL for his efforts, so there's no reason for the mercenary not to take the offer...

In [36]:
warnings.simplefilter(action='ignore', category=FutureWarning)

movie_ids = [9659, 8810, 9355, 76341]
tri_mad = pd.DataFrame()
for movie_id in movie_ids:
    url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
    response_movie = requests.get(url_movie)
    data_movie = response_movie.json()

    movie_info = {'ID do filme': data_movie['id'],
                  'Título': data_movie['title'],
                  'Data de lançamento': data_movie['release_date'],
                  'Gêneros': [genre['name'] for genre in data_movie['genres']],
                  'Votos': data_movie['vote_count'],
                  'Média de votos': data_movie['vote_average'],
                  'Orçamento': data_movie['budget'],
                  'Receita': data_movie['revenue'],
                  'Visão geral': data_movie['overview']}

    tri_mad = tri_mad.append(movie_info, ignore_index=True)

tri_mad.head()

,ID do filme,Título,Data de lançamento,Gêneros,Votos,Média de votos,Orçamento,Receita,Visão geral
0,9659,Mad Max,1979-04-12,"[Aventura, Ação, Thriller, Ficção científica]",3802,6.691,350000,100000000,"Em um futuro distópico não muito distante, os ..."
1,8810,Mad Max 2: A Caçada Continua,1981-12-24,"[Aventura, Ação, Thriller, Ficção científica]",3212,7.389,2000000,24600832,"No futuro o bem mais precioso é a gasolina, em..."
2,9355,Mad Max: Além da Cúpula do Trovão,1985-06-29,"[Ação, Aventura, Ficção científica]",2473,6.200,10000000,36230219,"Em uma era pós-apocalíptica, Mad Max chega a u..."
3,76341,Mad Max: Estrada da Fúria,2015-05-13,"[Ação, Aventura, Ficção científica]",20626,7.576,150000000,378858340,"Em um mundo apocalíptico, Max Rockatansky acre..."

## Franquia Alien (1979 - 2017)

In [37]:
# Pesquisando por todas as ocorrências de Alien

url_search = f"https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=pt-BR&query=Alien%"
response_search = requests.get(url_search)
data_search = response_search.json()

for movie in data_search['results']:
    print(f"ID do filme: {movie['id']}")
    print(f"Título do filme: {movie['title']}")
    print(f"Resumo do filme: {movie['overview']}")
    print("\n")

ID do filme: 348
Título do filme: Alien: O Oitavo Passageiro
Resumo do filme: Quando a tripulação da sonda espacial Nostromo responde a um pedido de socorro vindo de um planeta inóspito, eles descobrem uma forma de vida mortal que se reproduz dentro de humanos. Agora, a tripulação deve lutar para permanecer viva e impedir que a criatura chegue até a Terra.


ID do filme: 8077
Título do filme: Alien 3
Resumo do filme: A tenente Ripley é encarregada de ir a um planeta que é usado como colônia penal de segurança máxima. Este é o novo palco de assassinatos do Alien, que está matando tudo o que se move, menos a própria tenente Ripley, que aparentemente não é atacada pelo monstro.


ID do filme: 8078
Título do filme: Alien: A Ressurreição
Resumo do filme: Duzentos anos após seu suicídio, Ripley acorda. Cientistas conseguiram tirar a rainha alienígena de seu corpo e criaram alienígenas que escaparam, provocando terror. Eles precisam ser detidos.


ID do filme: 395
Título do filme: Alien vs. Predador
Resumo do filme: Uma pirâmide até então desconhecida é encontrada na Antártica através de satélites, fazendo com que uma equipe de cientistas e aventureiros seja enviada para investigar o local. Porém lá eles fazem uma descoberta atra: a pirâmide serve de abrigo para duas raças alienígenas extremamente violentas, que estão em guerra.


ID do filme: 941520
Título do filme: Alien Sniperess
Resumo do filme: A female sniper on military leave promises to fulfill her fiancé’s dying wish until she encounters a hostile alien invasion and is tasked with saving countless lives.


ID do filme: 39513
Título do filme: Paul: O Alien Fugitivo
Resumo do filme: Dois aficionados por ficção científica querem descobrir o que se encontra na infame Área 51 em Nevada e acabam encontrando um alienígena em fuga.


ID do filme: 440
Título do filme: Alien vs. Predador 2
Resumo do filme: Gunnison, uma pequena cidade localizada nas montanhas da área central do Colorado. Uma nave dos predatores aterrisa no local, mas os aliens que estavam escondidos nela conseguem matar a todos, com exceção de um. Para sobreviver ele precisará destruir todos os aliens remanescentes. Mas em meio a esta guerra há os humanos, residentes da pequena Gunnison, que assistem a esta batalha como vítimas e espectadores.


ID do filme: 312526
Título do filme: Alien Outpost
Resumo do filme: Uma unidade do exército no lugar mais hostil da terra, um posto avançado rodeado pelos últimos remanescentes de combatentes alienígenas (Heavies) de uma força de ataque invasora. O mundo pode ter esquecido os postos avançados, mas os Heavies planearam uma segunda invasão da Terra e os soldados são os únicos que podem impedi-la.


ID do filme: 550844
Título do filme: Expedição Alien
Resumo do filme: Depois que uma nave de exploração do espaço profundo descobre um planeta potencialmente habitável, uma equipe de escoteiros composta por indivíduos humanos e biorrobóticos é enviada para investigar os recursos do planeta. Uma vez no chão, sua missão de reconhecimento logo se transforma em uma batalha pela sobrevivência contra as formas de vida alienígenas hostis do planeta.


ID do filme: 457491
Título do filme: Alien: Covenant - Prólogo: O Cruzamento
Resumo do filme: O Cruzamento, um curta-metragem, prólogo oficial para Alien: Covenant, revela o que aconteceu com os membros da tripulação - Dra. Elizabeth Shaw e o sintético David - após os eventos de Prometheus. Instalados a bordo de uma nave abandonada dos Engenheiros, a Dra. Shaw repara David enquanto se dirigem ao mundo natal dos Engenheiros, que Shaw acredita serem os criadores da humanidade.


ID do filme: 10128
Título do filme: Missão Alien
Resumo do filme: No deserto de Mojave, Califórnia, uma pane na nave espacial obriga 300 mil humanóides a conviver com os humanos. Uma dupla de detetives diferentes - um terráqueo, e outro vindo do espaço - precisa superar as hostilidades e investigar um crime.


ID do filme: 126889
Título do filme: Alien: Covenant
Resumo do filme: Viajando pela galáxia, os tripulantes da nave colonizadora Covenant encontram um planeta remoto com ares de paraíso inexplorado. Encantados, eles acreditam na sorte e ignoram a realidade do local: uma terra sombria que guarda terríveis segredos e tem o sobrevivente David como habitante solitário.


ID do filme: 456504
Título do filme: Alien: Covenant - Prólogo: Última Refeição
Resumo do filme: O curta-metragem, prólogo para Alien: Covenant, ocorre a bordo da Covenant, uma nave de colonização da Weyland, em seu caminho para um planeta remoto para formar um novo assentamento humano. Antes que a equipe esteja preparada para entrar no criossono, os 14 membros da tripulação (todos casais) e seu andróide, Walter, desfrutam de sua refeição final juntos.


ID do filme: 529358
Título do filme: Código Alien
Resumo do filme: After deciphering a message found in a satellite, genius cryptographer Alex Jacobs finds himself being stalked by government agents and otherworldly beings.


ID do filme: 27909
Título do filme: Alien: A Criatura do Espaço
Resumo do filme: Two members of Greenpeace discover that a local factory sheds radioactive waste into an active volcano, which has created a terrifying creature that wreaks havoc in the area.


ID do filme: 593035
Título do filme: Guerra contra Aliens
Resumo do filme: Com a missão de investigar o misterioso desaparecimento de cientistas, militares americanos descobrem uma nova — e terrível — forma de vida.


ID do filme: 565591
Título do filme: Memory: As Origens de Alien
Resumo do filme: Documentário que explora as origens do filme Alien (1979), enraizadas nas mitologias grega e egípcia, em quadrinhos underground, na parasitologia, na ficção de H.P. Lovecraft, na arte de Francis Bacon e na simbiose entre o escritor Dan O’Bannon, o designer H.R. Giger e o diretor Ridley Scott.


ID do filme: 39916
Título do filme: Alien - O Monstro Assassino
Resumo do filme: A former astronaut helps a government agent and a police detective track the source of mysterious alien pod spores, filled with lethal flesh-dissolving acid, to a South American coffee plantation controlled by alien pod clones.


ID do filme: 120325
Título do filme: Invasão Alien
Resumo do filme: Quando um grupo de prisioneiros faz seus guardas de reféns durante um transporte de rotina, o que tinha começado como uma audaciosa e bem executada fuga, se transforma em algo mais ameaçador. Quando o grupo entra na calma cidade de Salena, os prisioneiros e os guardas são forçados a trabalharem juntos para sobreviver - ou morrer - diante de um terror muito maior do que podem imaginar.


ID do filme: 450642
Título do filme: Área 51: A Invasão Alien
Resumo do filme: Após décadas de teorias da conspiração e segredos, a CIA finalmente reconheceu a existência da Área 51. Mas isso não foi o suficiente, pois o que acontece lá dentro ainda é um mistério. Agora, um grupo heterogêneo, que inclui membros do exército e funcionários do governo, está preso nesse ambiente infame e precisa descobrir uma saída.

In [43]:
warnings.simplefilter(action='ignore', category=FutureWarning)

movie_ids = [348, 679, 8077, 8078, 70981, 126889]
tri_aliens = pd.DataFrame()
for movie_id in movie_ids:
    url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
    response_movie = requests.get(url_movie)
    data_movie = response_movie.json()

    movie_info = {'ID do filme': data_movie['id'],
                  'Título': data_movie['title'],
                  'Data de lançamento': data_movie['release_date'],
                  'Gêneros': [genre['name'] for genre in data_movie['genres']],
                  'Votos': data_movie['vote_count'],
                  'Média de votos': data_movie['vote_average'],
                  'Orçamento': data_movie['budget'],
                  'Receita': data_movie['revenue'],
                  'Visão geral': data_movie['overview']}

    tri_aliens = tri_aliens.append(movie_info, ignore_index=True)

tri_aliens.head(6)

,ID do filme,Título,Data de lançamento,Gêneros,Votos,Média de votos,Orçamento,Receita,Visão geral
0,348,Alien: O Oitavo Passageiro,1979-05-25,"[Terror, Ficção científica]",12912,8.144,11000000,104931801,Quando a tripulação da sonda espacial Nostromo...
1,679,Aliens: O Resgate,1986-07-18,"[Ação, Thriller, Ficção científica]",8540,7.923,18500000,183316455,"Cinquenta e quatro anos após escapar da ""Nostr..."
2,8077,Alien 3,1992-05-22,"[Ficção científica, Ação, Terror]",4942,6.352,50000000,159773545,A tenente Ripley é encarregada de ir a um plan...
3,8078,Alien: A Ressurreição,1997-11-12,"[Ficção científica, Terror, Ação]",4269,6.126,70000000,162000000,"Duzentos anos após seu suicídio, Ripley acorda..."
4,70981,Prometheus,2012-05-30,"[Ficção científica, Aventura, Mistério]",11042,6.525,130000000,403354469,Uma equipe de cientistas embarca em uma jornad...
5,126889,Alien: Covenant,2017-05-09,"[Ficção científica, Terror, Mistério]",7666,6.077,97000000,240891763,"Viajando pela galáxia, os tripulantes da nave ..."

In [10]:
# Juntando todos os datasets em um único para criar a função lambda em seguida

movie_ids = [120, 121, 122, 49051, 57158, 122917, 122917, 603, 604, 605, 624860, 218, 280, 296, 534, 87101, 290859, 105, 165, 196, 11, 1891, 1892, 1893, 1894, 1895, 140607, 181808, 181812, 9659, 8810, 9355, 76341, 348, 679, 8077, 8078, 70981, 126889]
franquias = pd.DataFrame()

movie_infos = [None] * len(movie_ids)

for i, movie_id in enumerate(movie_ids):
    url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
    response_movie = requests.get(url_movie)
    data_movie = response_movie.json()

    movie_info = {'ID TMDB': data_movie['id'],
                  'ID IMDB': data_movie['imdb_id'],
                  'Título': data_movie['title'],
                  'Data de lançamento': data_movie['release_date'],
                  'Gêneros': [genre['name'] for genre in data_movie['genres']],
                  'Duração (min)': data_movie['runtime'],
                  'Popularidade': data_movie['popularity'],
                  'Votos': data_movie['vote_count'],
                  'Média de votos': data_movie['vote_average'],
                  'Orçamento': data_movie['budget'],
                  'Receita': data_movie['revenue'],
                  'Produzido por': [name['name'] for name in data_movie["production_companies"]],
                  'Visão geral': data_movie['overview']}

    movie_infos[i] = movie_info

franquias = pd.DataFrame(movie_infos)
franquias.head(40)

,ID TMDB,ID IMDB,Título,Data de lançamento,Gêneros,Duração (min),Popularidade,Votos,Média de votos,Orçamento,Receita,Produzido por,Visão geral
0,120,tt0120737,O Senhor dos Anéis: A Sociedade do Anel,2001-12-18,"[Aventura, Fantasia, Ação]",179,107.868,22868,8.399,93000000,871368364,"[New Line Cinema, WingNut Films, The Saul Zaen...","Em uma terra fantástica e única, um hobbit rec..."
1,121,tt0167261,O Senhor dos Anéis: As Duas Torres,2002-12-18,"[Aventura, Fantasia, Ação]",180,83.827,19878,8.380,79000000,926287400,"[New Line Cinema, WingNut Films, The Saul Zaen...","Após a captura de Merry e Pippy pelos orcs, a ..."
2,122,tt0167260,O Senhor dos Anéis: O Retorno do Rei,2003-12-01,"[Aventura, Fantasia, Ação]",202,106.312,21759,8.477,94000000,1118888979,"[New Line Cinema, WingNut Films, The Saul Zaen...",O confronto final entre as forças do bem e do ...
3,49051,tt0903624,O Hobbit: Uma Jornada Inesperada,2012-11-26,"[Aventura, Fantasia, Ação]",182,85.966,17117,7.335,250000000,1021103568,"[Warner Bros. Pictures, Metro-Goldwyn-Mayer, N...","Como a maioria dos hobbits, Bilbo Bolseiro lev..."
4,57158,tt1170358,O Hobbit: A Desolação de Smaug,2013-12-11,"[Fantasia, Aventura, Ação]",161,64.460,12048,7.571,250000000,958400000,"[Warner Bros. Pictures, WingNut Films, New Lin...","Ao lado de um grupo de anões e de Gandalf, Bil..."
5,122917,tt2310332,O Hobbit: A Batalha dos Cinco Exércitos,2014-12-10,"[Ação, Aventura, Fantasia]",144,95.658,13063,7.310,250000000,956019788,"[Warner Bros. Pictures, WingNut Films, New Lin...",O dragão Smaug lança sua fúria ardente contra ...
6,122917,tt2310332,O Hobbit: A Batalha dos Cinco Exércitos,2014-12-10,"[Ação, Aventura, Fantasia]",144,95.658,13063,7.310,250000000,956019788,"[Warner Bros. Pictures, WingNut Films, New Lin...",O dragão Smaug lança sua fúria ardente contra ...
7,603,tt0133093,Matrix,1999-03-30,"[Ação, Ficção científica]",136,77.957,23365,8.204,63000000,463517383,"[Village Roadshow Pictures, Groucho II Film Pa...","Em um futuro próximo, Thomas Anderson (Keanu R..."
8,604,tt0234215,Matrix Reloaded,2003-05-15,"[Aventura, Ação, Thriller, Ficção científica]",138,47.255,9925,7.000,150000000,738599701,"[Village Roadshow Pictures, Silver Pictures, N...",Após derrotar as máquinas em seu combate inici...
9,605,tt0242653,Matrix Revolutions,2003-11-05,"[Aventura, Ação, Thriller, Ficção científica]",129,45.608,8921,6.700,150000000,424988211,"[Village Roadshow Pictures, NPV Entertainment,...","Após enfrentar os sentinelas no mundo real, Ne..."
10,624860,tt10838180,Matrix Resurrections,2021-12-16,"[Ficção científica, Ação, Aventura]",147,80.293,4818,6.500,190000000,156497322,"[Warner Bros. Pictures, Village Roadshow Pictu...",Em um mundo de duas realidades — a vida cotidi...
11,218,tt0088247,O Exterminador do Futuro,1984-10-26,"[Ação, Thriller, Ficção científica]",107,66.139,11585,7.641,6400000,78371200,"[Orion Pictures, Pacific Western, Hemdale Film...","Em um futuro próximo, a guerra entre humanos e..."
12,280,tt0103064,O Exterminador do Futuro 2: O Julgamento Final,1991-07-03,"[Ação, Thriller, Ficção científica]",136,74.173,11446,8.097,102000000,520000000,"[Lightstorm Entertainment, Carolco Pictures, P...",O jovem John Connor é a chave para a vitória d...
13,296,tt0181852,O Exterminador do Futuro 3: A Rebelião das Máq...,2003-07-02,"[Ação, Thriller, Ficção científica]",109,57.412,5942,6.144,200000000,435000000,"[Columbia Pictures, Intermedia Films, C-2 Pict...",Na intenção de concluir a missão ainda inacaba...
14,534,tt0438488,O Exterminador do Futuro 4: A Salvação,2009-05-20,"[Ação, Ficção científica, Thriller]",115,54.183,5889,6.039,200000000,371353001,"[Columbia Pictures, The Halcyon Company, Wonde...",John Connor é designado para liderar a resistê...
15,87101,tt1340138,O Exterminador do Futuro: Gênesis,2015-06-23,"[Ficção científica, Ação, Thriller, Aventura]",126,101.819,7732,5.920,155000000,440603537,"[Skydance, Paramount, Annapurna Pictures]","John Connor, líder da resistência humana contr..."
16,290859,tt6450804,O Exterminador do Futuro: Destino Sombrio,2019-10-23,"[Ficção científica, Ação]",128,60.504,4533,6.458,185000000,261119292,"[Lightstorm Entertainment, Skydance, 20th Cent...",Décadas após Sarah Connor impedir o Dia do Jul...
17,105,tt0088763,De Volta para o Futuro,1985-07-03,"[Aventura, Comédia, Ficção científica]",115,68.999,18076,8.312,19000000,381109762,"[Universal Pictures, Amblin Entertainment]","Marty McFly, um típico adolescente americano d..."
18,165,tt0096874,De Volta para o Futuro II,1989-11-22,"[Aventura, Comédia, Ficção científica]",108,36.985,11583,7.752,40000000,332000000,"[Universal Pictures, Amblin Entertainment]",Uma despretensiosa visita de McFly e Doc ao an...
19,196,tt0099088,De Volta para o Futuro III,1990-05-25,"[Aventura, Comédia, Ficção científica]",118,27.977,9482,7.466,40000000,244527583,"[Universal Pictures, Amblin Entertainment]",Presos em 1955 depois de um estranho estouro d...
20,11,tt0076759,Guerra nas Estrelas,1977-05-25,"[Aventura, Ação, Ficção científica]",121,85.097,18791,8.203,11000000,775398007,"[Lucasfilm Ltd., 20th Century Fox]",A princesa Leia é mantida refém pelas forças i...
21,1891,tt0080684,Guerra nas Estrelas: O Império Contra-Ataca,1980-05-20,"[Aventura, Ação, Ficção científica]",124,32.507,15459,8.392,18000000,538400000,[Lucasfilm Ltd.],As forças imperais comandadas por Darth Vader ...
22,1892,tt0086190,Guerra nas Estrelas: O Retorno de Jedi,1983-05-25,"[Aventura, Ação, Ficção científica]",135,33.118,14307,7.889,32350000,572700000,[Lucasfilm Ltd.],O imperador está supervisionando a construção ...
23,1893,tt0120915,Star Wars: Episódio I - A Ameaça Fantasma,1999-05-19,"[Aventura, Ação, Ficção científica]",136,32.299,13299,6.531,115000000,924317558,[Lucasfilm Ltd.],"Enquanto resgatam a Rainha Amidala, governante..."
24,1894,tt0121765,Star Wars: Episódio II - Ataque dos Clones,2002-05-15,"[Aventura, Ação, Ficção científica]",142,28.910,12058,6.552,120000000,649398328,[Lucasfilm Ltd.],"Com a missão de proteger a Senadora Amidala, A..."
25,1895,tt0121766,Star Wars: Episódio III - A Vingança dos Sith,2005-05-17,"[Aventura, Ação, Ficção científica]",140,35.374,12508,7.407,113000000,850000000,[Lucasfilm Ltd.],As Guerras Clônicas estão em pleno andamento e...
26,140607,tt2488496,Star Wars: O Despertar da Força,2015-12-15,"[Aventura, Ação, Ficção científica]",136,52.678,18114,7.296,245000000,2068223624,"[Lucasfilm Ltd., Bad Robot]",A queda de Darth Vader e do Império levou ao s...
27,181808,tt2527336,Star Wars: Episódio VIII - Os Últimos Jedi,2017-12-13,"[Aventura, Ação, Ficção científica]",150,49.536,14077,6.833,200000000,1332698830,[Lucasfilm Ltd.],A tranquila e solitária vida de Luke Skywalker...
28,181812,tt2527338,Star Wars: Episódio IX - A Ascensão Skywalker,2019-12-18,"[Aventura, Ação, Ficção científica]",141,54.523,8828,6.381,250000000,1074144248,"[Lucasfilm Ltd., Bad Robot]","Com o retorno do Imperador Palpatine, todos vo..."
29,9659,tt0079501,Mad Max,1979-04-12,"[Aventura, Ação, Thriller, Ficção científica]",93,28.067,3802,6.691,350000,100000000,"[Kennedy Miller Productions, Crossroads, Mad M...","Em um futuro distópico não muito distante, os ..."
30,8810,tt0082694,Mad Max 2: A Caçada Continua,1981-12-24,"[Aventura, Ação, Thriller, Ficção científica]",95,31.551,3212,7.389,2000000,24600832,[Kennedy Miller Productions],"No futuro o bem mais precioso é a gasolina, em..."
31,9355,tt0089530,Mad Max: Além da Cúpula do Trovão,1985-06-29,"[Ação, Aventura, Ficção científica]",107,25.708,2473,6.200,10000000,36230219,[Kennedy Miller Productions],"Em uma era pós-apocalíptica, Mad Max chega a u..."
32,76341,tt1392190,Mad Max: Estrada da Fúria,2015-05-13,"[Ação, Aventura, Ficção científica]",120,68.355,20629,7.576,150000000,378858340,"[Kennedy Miller Productions, Warner Bros. Pict...","Em um mundo apocalíptico, Max Rockatansky acre..."
33,348,tt0078748,Alien: O Oitavo Passageiro,1979-05-25,"[Terror, Ficção científica]",117,66.099,12913,8.144,11000000,104931801,"[Brandywine Productions, 20th Century Fox]",Quando a tripulação da sonda espacial Nostromo...
34,679,tt0090605,Aliens: O Resgate,1986-07-18,"[Ação, Thriller, Ficção científica]",135,68.035,8540,7.923,18500000,183316455,"[Brandywine Productions, SLM Production Group,...","Cinquenta e quatro anos após escapar da ""Nostr..."
35,8077,tt0103644,Alien 3,1992-05-22,"[Ficção científica, Ação, Terror]",114,27.058,4942,6.352,50000000,159773545,"[Brandywine Productions, 20th Century Fox]",A tenente Ripley é encarregada de ir a um plan...
36,8078,tt0118583,Alien: A Ressurreição,1997-11-12,"[Ficção científica, Terror, Ação]",109,27.862,4269,6.126,70000000,162000000,"[Brandywine Productions, 20th Century Fox]","Duzentos anos após seu suicídio, Ripley acorda..."
37,70981,tt1446714,Prometheus,2012-05-30,"[Ficção científica, Aventura, Mistério]",124,61.912,11044,6.525,130000000,403354469,"[Dune Entertainment, Scott Free Productions, B...",Uma equipe de cientistas embarca em uma jornad...
38,126889,tt2316204,Alien: Covenant,2017-05-09,"[Ficção científica, Terror, Mistério]",122,63.405,7666,6.077,97000000,240891763,"[Scott Free Productions, Brandywine Production...","Viajando pela galáxia, os tripulantes da nave ..."

## Criação da Função Lambda conforme especificações

In [ ]:
def lambda_handler(event, context):
    import requests
    import pandas as pd
    import numpy
    import json
    import boto3

    # Definindo a chave API
    api_key = "Minha Chave API TMDB"

    movie_ids = [120, 121, 122, 49051, 57158, 122917, 122917, 603, 604, 605, 624860, 218, 280, 296, 534, 87101, 290859, 105, 165, 196, 11, 1891, 1892, 1893, 1894, 1895, 140607, 181808, 181812, 9659, 8810, 9355, 76341, 348, 679, 8077, 8078, 70981, 126889]
    franquias = pd.DataFrame()

    movie_infos = [None] * len(movie_ids)

    for i, movie_id in enumerate(movie_ids):
        url_movie = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=pt-BR"
        response_movie = requests.get(url_movie)
        data_movie = response_movie.json()

        movie_info = {'ID TMDB': data_movie['id'],
                      'ID IMDB': data_movie['imdb_id'],
                      'Título': data_movie['title'],
                      'Data de lançamento': data_movie['release_date'],
                      'Gêneros': [genre['name'] for genre in data_movie['genres']],
                      'Duração (min)': data_movie['runtime'],
                      'Popularidade': data_movie['popularity'],
                      'Votos': data_movie['vote_count'],
                      'Média de votos': data_movie['vote_average'],
                      'Orçamento': data_movie['budget'],
                      'Receita': data_movie['revenue'],
                      'Produzido por': [name['name'] for name in data_movie["production_companies"]],
                      'Visão geral': data_movie['overview']}

        movie_infos[i] = movie_info

    franquias = pd.DataFrame(movie_infos)

    # Convertendo o DataFrame em uma string JSON
    franquias_json = franquias.to_json(orient='records')

    # Salvando os dados em um arquivo JSON no bucket S3
    s3 = boto3.resource('s3')
    bucket_name = "projeto-compass-filmes"
    file_name = "Raw/TMDB/JSON/2023/06/26/franquias.json"
    object = s3.Object(bucket_name, file_name)
    object.put(Body=franquias_json)

    # Retornando uma resposta
    return {
        'statusCode': 200,
        'body': json.dumps('Execução concluída com sucesso!')
    }